feat(icons): Add new icons collapse-vertical and expand-vertical
ithaka/pharos pull request #339
Opened 2022-05-03 18:23 UTC by jialin-he

**This change:** (check at least one)

- [x] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?

**What does this change address?**
We need a vertical version of collapse and expand icon.

**How does this change work?**
Add the icons to pharos.

2022-05-03 18:39 UTC, eslawski approved these changes

2022-05-04 00:36 UTC, satya-achanta-venkata approved these changes

2022-05-04 00:54 UTC, daneah commented on packages/pharos/tokens/assets/icons.json
> -      "collapse": { "value": "assets/icons/collapse.svg" },
If we're removing an icon and renaming another icon, these are both breaking changes.

2022-05-04 00:58 UTC, daneah commented on packages/pharos/tokens/assets/icons.json
> -      "collapse": { "value": "assets/icons/collapse.svg" },
You can consider deprecating the existing icons for now, and they can be removed in a later major version release. We don't have a convention for deprecating tokens at the moment, but Style Dictionary offers a reasonable suggestion [here](https://github.com/amzn/style-dictionary/blob/main/examples/advanced/tokens-deprecation/tokens/color/base.json#L9-L13) that would look like this:

```json
"collapse": {
    "value": "assets/icons/collapse.svg",
    "deprecated": true,
    "deprecated_comment": "Use collapse-<direction> instead"
}
```

2022-05-04 01:00 UTC, daneah requested changes

2022-05-04 01:00 UTC, daneah commented on packages/pharos/tokens/assets/icons.json
> -      "expand": { "value": "assets/icons/expand.svg" },
If we're removing an icon and renaming another icon, these are both breaking changes. You can consider deprecating the existing icons for now, and they can be removed in a later major version release. We don't have a convention for deprecating tokens at the moment, but Style Dictionary offers a reasonable suggestion [here](https://github.com/amzn/style-dictionary/blob/main/examples/advanced/tokens-deprecation/tokens/color/base.json#L9-L13) that would look like this:

```json
"collapse": {
    "value": "assets/icons/collapse.svg",
    "deprecated": true,
    "deprecated_comment": "Use collapse-<direction> instead"
}
```

2022-05-04 14:52 UTC, daneah commented on packages/pharos/tokens/assets/icons.json
> +        "value": "assets/icons/collapse.svg",
```suggestion
        "value": "assets/icons/shift-right.svg",
```

2022-05-04 15:06 UTC, daneah approved these changes

2022-05-05 16:21 UTC, merged