Docs: Update flex attribute docs for links
ithaka/pharos pull request #493
Opened 2023-02-09 16:40 UTC by NazimHAli

**This change:** (check at least one)

- [ ] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [x] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [ ] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
Adds extra information for users to use the `flex` attribute when using a nested heading so that it's visually accessible in all browsers.

2023-02-09 16:42 UTC, daneah requested changes

2023-02-09 16:42 UTC, daneah commented on packages/pharos/src/components/link/pharos-link.ts
> +   * the blue outline is rendered on focus for Chrome and Safari (works as expected on Firefox).
Is there broader guidance that can be given here? I suspect headings might not be the only thing affected, or if they are someone might need to understand why here.

2023-02-10 11:44 UTC, daneah approved these changes
This looks good, I wonder if there are other broader reasons to use `flex` that aren't captured but we can generalize the guidance as needed later on.

2023-02-10 15:35 UTC, NazimHAli commented
> This looks good, I wonder if there are other broader reasons to use `flex` that aren't captured but we can generalize the guidance as needed later on.

I haven't had a chance to review general cases, if it comes to mind will open another PR.

2023-02-13 14:45 UTC, chrisjbrown approved these changes

2023-02-22 01:49 UTC, merged