Icons: Add audio icons
ithaka/pharos pull request #497
Opened 2023-02-21 17:46 UTC by jialin-he

**This change:** (check at least one)

- [x] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
Add audio icons

**How does this change work?**
Add the svg

2023-02-21 17:51 UTC, daneah requested changes
@jialin-he @lorilundy711 I see that the `play`/`play-large` and `pause`/`pause-large` icons are visually identical. Because SVG is able to scale to any desired size, what is the value of having the distinct icons?

2023-02-22 14:40 UTC, lorilundy711 commented
Hi @daneah, thanks for bringing this up! We were following the pattern of chevron and chevron-large: https://pharos.jstor.org/storybook/?path=/story/webcomponents_components-icon--names

We did bump up the stroke on the large play icon to 2.5 as the designers felt that it needed a bit more visual weight.

2023-02-22 14:46 UTC, daneah commented
@lorilundy711 thanks for the details!

2023-02-22 14:46 UTC, daneah approved these changes

2023-02-22 14:48 UTC, chrisjbrown approved these changes

2023-02-22 19:43 UTC, merged