Update the missing href value
ithaka/pharos pull request #508
Opened 2023-04-01 10:59 UTC by Yasir761

**This change:** (check at least one)

fixes #507 

- [ ] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [ ] No

**Is the:** (complete all)

- [ ] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [ ] Test suite(s) passing?
- [ ] Code coverage maximal?
- [ ] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
A clear and concise description or a direct link to an issue [e.g. #15]
If adding a feature, a rationale for its addition goes here.

**How does this change work?**
A clear, detailed description of how this change addresses the issue.
This could be a bullet list if there are several moving parts.

**Additional context**
Add any other context here.

2023-04-01 11:37 UTC, daneah commented
@Yasir761 thank you for contributing! The issue you're referencing is actually a problem only with the site and the example components rendered there, rather than an issue with the component itself. The component should not change, here—just the props being supplied to it in the example on the site!

2023-04-01 11:38 UTC, daneah requested changes
@Yasir761 thank you for contributing! The issue you're referencing is actually a problem only with the site and the example components rendered there, rather than an issue with the component itself. The component should not change, here—just the props being supplied to it in the example on the site!

2023-04-05 23:42 UTC, daneah commented
@Yasir761 are you planning to address the requested changes?

2023-04-10 18:41 UTC, Yasir761 commented
> thank you for contributing! The issue you're referencing is actually a problem only with the site and the example components rendered there, rather than an issue with the component itself. The component should not change, here—just the props being supplied to it in the example on the site!

Yes, I'm not able to find the prop where I can pass it.

Also, sorry for being late reply.

2023-05-02 16:48 UTC, closed without merging