docs: update accessibility sections for components
ithaka/pharos pull request #53
Opened 2021-05-28 17:03 UTC by Lham42

**This change:** (check at least one)

- [ ] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [x] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite(s) passing?
- [x] Code coverage maximal?
- [x] Changeset added?

**What does this change address?**
The accessibility sections of multiple sections had opportunity to be much more through and specific.

**How does this change work?**
This changes add and replaces content currently in the accessibility section with the newly updated content from the google docs.

**Additional context**
Alert component still must be completed.

2021-06-01 04:14 UTC, SMQuazi requested changes

2021-06-01 04:14 UTC, SMQuazi commented on packages/pharos-site/static/guidelines/checkbox.docs.mdx
> +        {' '}
These strings appear due to auto-formatting. Feel free to remove these

2021-06-01 19:40 UTC, Niznikr commented on packages/pharos-site/static/guidelines/select.docs.mdx
> +        {' '}
Seeing some here too

2021-06-02 13:13 UTC, Niznikr approved these changes

2021-06-02 16:09 UTC, SMQuazi approved these changes

2021-06-02 18:39 UTC, merged