Modal: "Base" and "No footer" stories fixed in Storybook
ithaka/pharos pull request #530
Opened 2023-05-18 13:52 UTC by HassanTanveer

**This change:** (check at least one)

- [ ] Adds a new feature
- [x] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [x] No

**Is the:** (complete all)

- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [ ] Test suite(s) passing?
- [ ] Code coverage maximal?
- [x] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
Fixes #527 

1. Fixed React Storybook for Modal
2. Fixed Web Component Storybook for Modal

**How does this change work?**
- 'id' and 'data-modal-id' were missing from Base and No Footer Modal Storybook

**Additional context**
Add any other context here.

2023-05-18 18:57 UTC, daneah requested changes
Thanks for this submission! One thing to update regarding the release version.

2023-05-18 18:57 UTC, daneah commented on .changeset/new-pianos-invite.md
> +'@ithaka/pharos': major
```suggestion
'@ithaka/pharos': patch
```

2023-05-18 19:02 UTC, HassanTanveer commented
> Thanks for this submission! One thing to update regarding the release version.

Done!

2023-05-19 15:27 UTC, daneah approved these changes

2023-05-19 15:27 UTC, merged