Docs/elevation
ithaka/pharos pull request #643
Opened 2023-10-25 20:12 UTC by nkamau

**This change:** (check at least one)

- [ ] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [ ] No

**Is the:** (complete all)

- [ ] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [ ] Test suite(s) passing?
- [ ] Code coverage maximal?
- [ ] Changeset added?
- [ ] Component status page up to date?

**What does this change address?**
A clear and concise description or a direct link to an issue [e.g. #15]
If adding a feature, a rationale for its addition goes here.

**How does this change work?**
A clear, detailed description of how this change addresses the issue.
This could be a bullet list if there are several moving parts.

**Additional context**
Add any other context here.

2023-11-07 22:57 UTC, daneah requested changes

2023-11-07 22:57 UTC, daneah commented on install_nvm.sh
This file should be deleted.

2023-11-07 22:57 UTC, daneah commented on packages/pharos-site/src/pages/brand-expressions/elevation.mdx
> +    <div style="width: 201px; height: 142px; flex-shrink: 0; border-radius: 5px; box-shadow: 0px 4px 8px 3px rgba(18, 18, 18, 0.15), 0px 1px 2px 0px rgba(18, 18, 18, 0.30);"></div>
Can lines like these throughout the page use the tokens as well?

2023-11-07 22:57 UTC, daneah commented on packages/pharos-site/static/images/brand-expressions/elevation/elevation_stack_guide.jpg
This image uses language that isn't really part of the system, and references things that only live on the platform as usages of the system (such as the "search results dropdown"). We should be really careful with mixing language like this from a governance perspective, because it degrades clarity and can create confusion.

2023-11-07 22:57 UTC, daneah commented on packages/pharos/tokens/elevation.json
> +  }
```suggestion
{
    "elevation": {
      "level": {
        "1": { "value": "0px 1px 2px 0px rgba(18, 18, 18, 0.3),0px 1px 3px 1px rgba(18, 18, 18, 0.15)" },
        "2": { "value": "0px 1px 2px 0px rgba(18, 18, 18, 0.3),0px 2px 6px 2px rgba(18, 18, 18, 0.15)" },
        "3": { "value": "0px 1px 2px 0px rgba(18, 18, 18, 0.3),0px 4px 8px 3px rgba(18, 18, 18, 0.15)" },
        "4": { "value": "0px 1px 2px 0px rgba(18, 18, 18, 0.3),0px 6px 10px 4px rgba(18, 18, 18, 0.15)" },
        "5": { "value": "0px 1px 2px 0px rgba(18, 18, 18, 0.3),0px 8px 12px 6px rgba(18, 18, 18, 0.15)" }
      }
    }
  }
```

2023-11-08 20:27 UTC, nkamau commented on packages/pharos-site/static/images/brand-expressions/elevation/elevation_stack_guide.jpg
Clarifying question for you: Are you saying that the language used in the diagram should use the terminology that is used in Storybook? Because "search result dropdown" is a descriptor of something that _happens_ on the platform itself and isn't in storybook at all...?

2023-11-08 20:55 UTC, daneah commented on packages/pharos-site/static/images/brand-expressions/elevation/elevation_stack_guide.jpg
I'm not really speaking at all about Storybook; I'm speaking about what's in Pharos as a proper part of the system, i.e. Pharos should be as self-contained as possible!

2023-11-09 13:54 UTC, nkamau commented on packages/pharos-site/static/images/brand-expressions/elevation/elevation_stack_guide.jpg
Okay, so for the content on each level, only Pharos system language should be used. Out of the content in the elevation diagram, "search results dropdown (predictive search)" is the one that doesn't follow the "self-contained" rule and shouldn't be there?

2023-11-29 22:11 UTC, daneah approved these changes

2023-11-29 22:25 UTC, merged