Dropdown Menu: Add default elevation
ithaka/pharos pull request #684
Opened 2024-02-09 14:38 UTC by brentswisher

**This change:** (check at least one)

- [X] Adds a new feature
- [ ] Fixes a bug
- [ ] Improves maintainability
- [ ] Improves documentation
- [ ] Is a release activity

**Is this a breaking change?** (check one)

- [ ] Yes
- [X] No

**Is the:** (complete all)

- [X] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [X] Test suite(s) passing?
- [X] Code coverage maximal?
- [X] Changeset added?
- [X] Component status page up to date?

**What does this change address?**
Closes #662.
Adds default elevation to the dropdown-menu component.

**How does this change work?**
Adds a `box-shadow` set to the `pharos-elevation-level-3` design token to the dropdown-menu component

**Screenshot**
Before:
<img width="236" alt="Screenshot 2024-02-09 at 9 29 24 AM" src="https://github.com/ithaka/pharos/assets/6653970/d21e68d6-deb8-4c80-9f5c-8d7431318200">

After:
<img width="236" alt="Screenshot 2024-02-09 at 9 32 39 AM" src="https://github.com/ithaka/pharos/assets/6653970/1d3d76ad-acd0-438b-bfc4-9fa887343e20">

2024-02-09 14:39 UTC, daneah approved these changes

2024-02-09 15:16 UTC, sirrah-tam approved these changes

2024-02-09 15:17 UTC, mtorres3 approved these changes
Looks like this change may have been already added to the `develop` branch

2024-02-09 15:46 UTC, nkamau approved these changes

2024-02-09 16:13 UTC, nkamau requested changes
Hold off a sec.

2024-02-12 21:56 UTC, nkamau approved these changes

2024-02-13 15:23 UTC, brentswisher commented
@nkamau  - it looks like there is a border here after all: (With Border on left, without border on right)

Just wanted to double-check the border should be removed? 

<img width="785" alt="Screenshot 2024-02-13 at 10 21 56 AM" src="https://github.com/ithaka/pharos/assets/6653970/5429b5a7-ea85-4150-b87b-138da73219b1">

2024-02-13 16:37 UTC, nkamau approved these changes

2024-02-13 16:43 UTC, merged